# Generated by Django 5.1.4 on 2025-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0003_group_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ManyToManyField(
                related_name="tasks", to="mindplan_manager.group"
            ),
        ),
    ]
