# Generated by Django 5.1.4 on 2025-01-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0004_remove_group_tasks_task_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="group",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="mindplan_manager.group"
            ),
        ),
    ]
