# Generated by Django 5.1.4 on 2025-01-15 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0005_alter_task_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Tag",
        ),
        migrations.RemoveField(
            model_name="task",
            name="group",
        ),
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="mindplan_manager.tag"
            ),
        ),
    ]
