# Generated by Django 5.1.4 on 2025-01-15 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0006_rename_group_tag_remove_task_group_task_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Group",
        ),
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="mindplan_manager.group"
            ),
        ),
    ]
