# Generated by Django 5.1.4 on 2025-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0008_tag_remove_group_owner_remove_task_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgroup",
            name="default_status",
            field=models.BooleanField(default=False),
        ),
    ]
