# Generated by Django 5.1.4 on 2025-02-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindplan_manager", "0009_taskgroup_default_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskgroup",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
